import 'package:neuro_pairs/domain/utils/enums/pairs_category_type.dart';

abstract final class OfflineCardsAssets {
  static const _mainPath = 'assets/raw/offline_unique/';
  static const _numbersAndLetters = '${_mainPath}numbers&letters/';
  static const _figures = '${_mainPath}figures/';
  static const _flags = '${_mainPath}flags/';
  static const _colors = '${_mainPath}colors/';

  static const categoryAssets = <OfflinePairsCategoryType, List<String>>{
    OfflinePairsCategoryType.numbersAndLetters: numbersAndLetters,
    OfflinePairsCategoryType.figures: figures,
    OfflinePairsCategoryType.countryFlags: flags,
    OfflinePairsCategoryType.colors: colors,
  };

  static const colors = <String>[
    '${_colors}color1.png',
    '${_colors}color2.png',
    '${_colors}color3.png',
    '${_colors}color4.png',
    '${_colors}color5.png',
    '${_colors}color6.png',
    '${_colors}color7.png',
    '${_colors}color8.png',
    '${_colors}color9.png',
    '${_colors}color10.png',
    '${_colors}color11.png',
    '${_colors}color12.png',
    '${_colors}color13.png',
    '${_colors}color14.png',
    '${_colors}color15.png',
    '${_colors}color16.png',
    '${_colors}color17.png',
    '${_colors}color18.png',
  ];

  static const flags = <String>[
    '${_flags}austria.png',
    '${_flags}belarus.png',
    '${_flags}brazil.png',
    '${_flags}canada.png',
    '${_flags}chile.png',
    '${_flags}china.png',
    '${_flags}czech.png',
    '${_flags}denmark.png',
    '${_flags}finland.png',
    '${_flags}france.png',
    '${_flags}germany.png',
    '${_flags}greece.png',
    '${_flags}hol.png',
    '${_flags}hungary.png',
    '${_flags}india.png',
    '${_flags}israel.png',
    '${_flags}italy.png',
    '${_flags}japan.png',
    '${_flags}kazakhstan.png',
    '${_flags}moldova.png',
    '${_flags}poland.png',
    '${_flags}russia.png',
    '${_flags}south_korea.png',
    '${_flags}spain.png',
    '${_flags}sweden.png',
    '${_flags}taiwan.png',
    '${_flags}turkey.png',
    '${_flags}uk.png',
    '${_flags}ukraine.png',
    '${_flags}usa.png',
  ];

  static const numbersAndLetters = <String>[
    '${_numbersAndLetters}1.png',
    '${_numbersAndLetters}2.png',
    '${_numbersAndLetters}3.png',
    '${_numbersAndLetters}4.png',
    '${_numbersAndLetters}5.png',
    '${_numbersAndLetters}6.png',
    '${_numbersAndLetters}7.png',
    '${_numbersAndLetters}8.png',
    '${_numbersAndLetters}9.png',
    '${_numbersAndLetters}A.png',
    '${_numbersAndLetters}B.png',
    '${_numbersAndLetters}C.png',
    '${_numbersAndLetters}D.png',
    '${_numbersAndLetters}E.png',
    '${_numbersAndLetters}F.png',
    '${_numbersAndLetters}G.png',
    '${_numbersAndLetters}H.png',
    '${_numbersAndLetters}I.png',
    '${_numbersAndLetters}J.png',
    '${_numbersAndLetters}K.png',
    '${_numbersAndLetters}L.png',
    '${_numbersAndLetters}M.png',
    '${_numbersAndLetters}N.png',
    '${_numbersAndLetters}O.png',
    '${_numbersAndLetters}P.png',
    '${_numbersAndLetters}Q.png',
    '${_numbersAndLetters}R.png',
    '${_numbersAndLetters}S.png',
    '${_numbersAndLetters}T.png',
    '${_numbersAndLetters}U.png',
    '${_numbersAndLetters}V.png',
    '${_numbersAndLetters}W.png',
    '${_numbersAndLetters}X.png',
    '${_numbersAndLetters}Y.png',
    '${_numbersAndLetters}Z.png',
  ];

  static const figures = <String>[
    '${_figures}figure1.png',
    '${_figures}figure2.png',
    '${_figures}figure3.png',
    '${_figures}figure4.png',
    '${_figures}figure5.png',
    '${_figures}figure6.png',
    '${_figures}figure7.png',
    '${_figures}figure8.png',
    '${_figures}figure9.png',
    '${_figures}figure10.png',
    '${_figures}figure11.png',
    '${_figures}figure12.png',
    '${_figures}figure13.png',
    '${_figures}figure14.png',
    '${_figures}figure15.png',
    '${_figures}figure16.png',
    '${_figures}figure17.png',
    '${_figures}figure18.png',
  ];
}
