// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfUEIQsNpmiyN7rm2qG4709VFUAvq5IuY',
    appId: '1:181820053755:android:affd5db1a627b48d04f85e',
    messagingSenderId: '181820053755',
    projectId: 'neuro-pairs',
    storageBucket: 'neuro-pairs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1oVQWDNcty1ecHtRbVcbiMComCMPzKA',
    appId: '1:181820053755:ios:228d4a11e2563f4504f85e',
    messagingSenderId: '181820053755',
    projectId: 'neuro-pairs',
    storageBucket: 'neuro-pairs.appspot.com',
    androidClientId: '181820053755-6gpcniv5eshjfftuol778tftn60tqrq1.apps.googleusercontent.com',
    iosClientId: '181820053755-pseqtrcl5tjdtf32fktm2t95dfnbvrpa.apps.googleusercontent.com',
    iosBundleId: 'com.requestfordinner.neuropairs',
  );

}